### ISSUE TITLE
Unified Brioche at CLV menu

### ISSUE THREAD

**Issue by shrotia** [hlxsites/caesars-screens#26]
As part of this issue, create the unified menu for Brioche at CLV.
http://marketeammenuclvbrioche.com/Menu.pdf

This menu already implemented and ready for the integration with the WebSite & Screens.
https://main--caesars-screens--hlxsites.hlx.live/screens/menus/cafe

Though few enhancements could be considered:
1. On WebSite, it should get loaded instantly (as we have to replace existing PDF based menu) - no JS based responsiveness/scalability etc.. Also it should not look distorted
2. On Browser, Food & Beverages section should render in side by side or stacked based on the browser's dimension.

**Comment by div8063** [comment]
Observed a few issues with the existing menu:

- Menu calibration for player playback was not working. Also, the calibration wasn't accurate since there was a slight overflow of menu items intermittently.
- Menu responsiveness for web playback needs fixing for different resolutions.

FIxing these in PR: https://github.com/hlxsites/caesars-screens/pull/27/files

**Comment by div8063** [comment]
Menu url: https://main--caesars-screens--hlxsites.hlx.page/screens/menus/cafe
